version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:7.1.0
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: "Checking Versions"
          command: |
              node --version
              npm --version
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: update-process-nextick-args
          command: npm install -g process-nextick-args
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
